# Generated by Django 5.1.3 on 2025-08-08 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(choices=[('cleaning', 'Cleaning Services'), ('moving', 'Moving & Delivery'), ('assembly', 'Furniture Assembly'), ('gardening', 'Gardening & Landscaping'), ('handyman', 'Handyman Services'), ('other', 'Other Services')], max_length=50)),
                ('subcategory', models.CharField(max_length=100)),
                ('task_description', models.TextField(max_length=500)),
                ('address', models.CharField(max_length=255)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(choices=[('Morning', 'Morning (8am - 12pm)'), ('Afternoon', 'Afternoon (12pm - 5pm)'), ('Evening', 'Evening (5pm - 9pm)')], max_length=20)),
                ('is_flexible', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('Hourly', 'Hourly Rate'), ('Fixed', 'Fixed Price')], max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=8)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('helper_brings_tools', models.BooleanField(default=False)),
                ('background_check_required', models.BooleanField(default=False)),
                ('insurance_needed', models.BooleanField(default=False)),
                ('experience_required', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='helpersapp.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='request_photos/')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='helpersapp.servicerequest')),
            ],
        ),
        migrations.DeleteModel(
            name='HelpRequest',
        ),
    ]
