# Generated by Django 5.1.3 on 2025-08-10 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
        ('helpersapp', '0003_servicerequest_payment_status_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Helper',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='accepted_helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_requests', to='helpers.helper'),
        ),
    ]
