# Generated by Django 5.1.3 on 2025-08-10 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
        ('helpersapp', '0004_delete_helper_servicerequest_accepted_helper'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender_helper', models.ForeignKey(blank=True, help_text='Set if the sender is a Helper', null=True, on_delete=django.db.models.deletion.CASCADE, to='helpers.helper')),
                ('sender_user', models.ForeignKey(blank=True, help_text='Set if the sender is a User', null=True, on_delete=django.db.models.deletion.CASCADE, to='helpersapp.user')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='helpersapp.servicerequest')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
