# Generated by Django 5.1.3 on 2025-08-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpersapp', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='otp_code',
            field=models.CharField(blank=True, help_text='6-digit code for verifying job completion', max_length=6, null=True),
        ),
    ]
