# Generated by Django 5.1.3 on 2026-02-01 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0003_notification'),
        ('helpersapp', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper_notifications_userapp', to='helpers.helper'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requester_notifications', to='helpersapp.user'),
        ),
    ]
