# Generated by Django 5.1.3 on 2025-08-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
