# Generated by Django 5.1.3 on 2026-02-27 02:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
